services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.32.3
    ports:
      - "8080:8080"
      - "50051:50051"
    volumes:
      - ./weaviate_data:/var/lib/weaviate
    restart: unless-stopped
    depends_on:
      - t2v-transformers
    environment:
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080'
      QUERY_DEFAULTS_LIMIT: 50
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      AUTHENTICATION_APIKEY_ENABLED: 'false'
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: 'YOUR_PASSWORD'
      AUTHENTICATION_APIKEY_USERS: 'YOUR_USER_NAME'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers'
      ENABLE_TOKENIZER_GSE: 'true'
      CLUSTER_HOSTNAME: 'node1'

  t2v-transformers:
    image: cr.weaviate.io/semitechnologies/transformers-inference:baai-bge-m3-onnx
    restart: unless-stopped
    environment:
      ENABLE_CUDA: '0'
